global using FluentValidation;
global using MediatR;
global using System.Net;
global using MarstonX.Domain.Entities;
global using MarstonX.Domain.Common;
global using MarstonX.Application.Exceptions;
global using System.Text.Json;
global using MarstonX.Application.Wrappers;
global using Microsoft.Extensions.Configuration;
global using Microsoft.Extensions.DependencyInjection;
global using System.Reflection;
global using AutoMapper;
global using MarstonX.Application.Behaviours;
global using MarstonX.Application.IRepository.Sql;
global using System.ComponentModel.DataAnnotations;
global using MarstonX.Application.Handlers.Auth.DTO;
global using System.IdentityModel.Tokens.Jwt;
global using MarstonX.Infrastructure.Helper;
global using Newtonsoft.Json;
global using MarstonX.Infrastructure.Common;
global using static MarstonX.Infrastructure.Common.CommonEnum;
global using JsonSerializer = System.Text.Json.JsonSerializer;