<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Handlers\Users\DTO\" />
    <Folder Include="Handlers\Users\Mappers\" />
    <Folder Include="Handlers\Users\Validator\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="8.1.0" />
    <PackageReference Include="FluentValidation.AspNetCore" Version="11.2.1" />
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" Version="11.4.0" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Infra\MarstonX.Infrastructure\MarstonX.Infrastructure.csproj" />
    <ProjectReference Include="..\MarstonX.Domain\MarstonX.Domain.csproj" />
  </ItemGroup>

</Project>
